### ISSUE TITLE
Ground Explosion

### ISSUE THREAD

**Issue by Vastlee** [inland-empire-software-development/Spout#6]
Create a script named GroundExplosion.cs

Serialize Fields:
float blastForce, blastArea, & blastUpdwardMod

Private Fields:
Camera mainCamera
LayerMask groundLayer & dropsLayer

Private ReadOnly Fields:
float blastForceMultiplier

Private Methods:
CheckGroundForClick()
Explode(Vector3 targetPos)
TotalBlastForce()

Behavior:
At the start the script should cache the camera & the 2 layers. 

The Update should watch for the Left Mouse to be clicked. When true, should call CheckGroundForClick()

CheckGroundForClick should shoot a ray from the mainCamera to the mouse position & see if it collides with the ground layer. If so, should call Explode with the hit position

When Explode is called it should create an overlapshere looking for objects on the Drops layer. When found should Add explosive force at the target position, with the TotalBlastForce() at the targetPos, with a blastArea and the blastUpdwardMod.

TotalBlastForce should return the blastForce multiplied by the blastForceModifier.

**Comment by Tetrergeru** [comment]
I would like to do it, if you don't mind.

**Comment by Vastlee** [comment]
You can do it!
